### ISSUE TITLE
"sudo ./skp" Command not Found

### ISSUE THREAD

**Issue by Moose1002** [Blasteroids/StageKitPied#1]
I'm working on setting this up for myself and I've gotten everything going up to the point where you actually run the tool itself and for whatever reason the ./skp command says it's not found and I can't figure out an alternative way to run the skp file. 

I'm running it on a Raspberry Pi 3b+ on the 32bit legacy raspberry pi OS.
I know this is an older project but I would really like to get this going. So any help would be greatly appreciated!

**Comment by Blasteroids** [comment]
Hello, the compiled program is for 64bit.  If you need to run on 32bit OS then please compile from the source.  I currently don't have access to a pi to test and can't say if there will be issues.  Please feel free to give this go.

From the command line install compiler & libusb with this :- 

`sudo apt-get install build-essential libusb-1.0-0-dev`

Then copy the project into a folder and from that folder run this command :-

`make all`

Then use the new compiled skp program.  Good luck!  Please let me know how it goes :)

Edit: Please re-open ticket if this didn't solve the issue.

**Comment by Moose1002** [comment]
Still no luck even with the proposed fixes, could we continue this via discord for easier communication on the issue? I've already sent you a message if that's alright.
