### ISSUE TITLE
sudo ./skp: Command not found - Raspian

### ISSUE THREAD

**Issue by AMurderOfCrows** [Blasteroids/StageKitPied#2]
Same as the previous issue, so this isn't resolved. 

Brand new install as of 2024-06-06 (i literally turned it on for the first time about an hour before starting this issue).

Raspberry Pi 5 running ARM64 version of Raspian/Raspberry Pi OS, fully updated tonight before starting.

Steps to Reproduce:

1. Fresh install of Raspian/Raspberry Pi OS (current as of 2024-06-04) on Raspberry Pi 5
2. Connect to internet and fully update
3. download SKP and lights.ini files from this git
4. place in folder on desktop
5. run terminal as root
6. navigate to folder mentioned
7. run command 

I think that whatever was used to make/execute the skp file available in the github has been deprecated. i understand that i'll likely need to build from source, but based on the previous issue that was seen, perhaps it would suit me better in the short term to know what version of the OS is being run that built the existing executable.
 
 
Slight Update:
It may also be a lack of understanding on how exactly to run this app. It's obviously seen by the system as being an executable, but it isn't clear on how it is run.

I opened a root enabled file manager, then double-clicked the file and it asked me if i wanted to run it. when i did, a terminal window appeared with "skp" in the title bar and no info displayed. this indicates SOMETHING is happening, which is good, but as i want to either run this at start up or run it through ssh, i'm not sure what to do.

```

root@raspberrypi:/home/amurderofcrows/Desktop/SKP# sudo ./skp
sudo: ./skp: command not found
root@raspberrypi:/home/amurderofcrows/Desktop/SKP# ^C
root@raspberrypi:/home/amurderofcrows/Desktop/SKP# hostnamectl
 Static hostname: raspberrypi
       Icon name: computer
      Machine ID: 941c286fad504dfc9fd6f130c9d684c7
         Boot ID: 99bfc4c175dc43f2892352703d7120f0
Operating System: Debian GNU/Linux 12 (bookworm)  
          Kernel: Linux 6.6.31+rpt-rpi-2712
    Architecture: arm64
root@raspberrypi:/home/amurderofcrows/Desktop/SKP# ^C
root@raspberrypi:/home/amurderofcrows/Desktop/SKP# 
```

**Comment by Blasteroids** [comment]
Compiled executable on github was created for 32 bit os.  Please compile if you need for 64 bit.  There was a missing folder (objects) that the makefile uses, which I've now included.

**Comment by AMurderOfCrows** [comment]
64-bit compiled properly with assistance and the recent changes. still testing but the "command not found" issue seems to be resolved.

recommend that maybe a package be created for 32-bit and 64-bit?
